jobs:
  copy-branch:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - continue-on-error: true
      run: 'git config user.name github-actions

        git config user.email github-actions@github.com

        git merge origin/main

        git push

        '
name: Duplicates main to old master branch
on:
  repository_dispatch:
    types: trigger-ga___copy-branch.yml
